import type { AIConfig } from "@/lib/janggi/ai";
import type { Lines } from "@/lib/botTalk";

/** 장기 AI 상대: 한국 위인 (약한 순). 급수는 대략적인 체감 기준 */
export interface JanggiBot {
  id: string;
  name: string;
  rank: string;
  desc: string;
  emoji: string;
  ai: AIConfig;
  lines: Lines;
}

export const JANGGI_BOTS: JanggiBot[] = [
  {
    id: "jangyeongsil",
    name: "장영실",
    rank: "18급",
    desc: "발명은 잘하는데 장기는…",
    emoji: "⚙️",
    ai: { depth: 1, ms: 300, noise: 3, blunder: 0.4 },
    lines: {
      greet: [
        "측우기 만들다 잠깐 쉬러 왔소이다. 한 판 둡시다!",
        "장기도 결국 이치를 따지는 일이겠지요?",
      ],
      move: [
        "오호, 그 수는 마치 정교한 자격루 같구려",
        "꽤 괜찮은 수군요",
        "흠… 원리를 좀 더 연구해야겠소",
      ],
      userCapture: ["아이고, 그건 설계 실수였소", "부품 하나가 빠졌구려…"],
      userBigCapture: ["내 차가! 다시 만들어야겠소 😵", "이런, 핵심 부품을 잃었구려"],
      userCheck: ["장군이라니! 해시계 보듯 침착하게…"],
      aiCapture: ["오, 이게 되는구려! 🎉", "실험 성공이오!"],
      aiCheck: ["장군이오! …맞게 부른 거 맞지요?"],
      undo: ["실험엔 실패가 따르는 법, 물러드리리다"],
      aiWin: ["이겼소?! 전하께 보고드려야겠소!"],
      aiLose: ["역시 장기는 어렵구려. 발명이나 하러 가야겠소 😅"],
      draw: ["비겼구려. 이것도 귀한 데이터요"],
    },
  },
  {
    id: "heojun",
    name: "허준",
    rank: "15급",
    desc: "약은 잘 짓는데 수는 아직",
    emoji: "🌿",
    ai: { depth: 1, ms: 300, noise: 2.4, blunder: 0.28 },
    lines: {
      greet: ["동의보감 쓰다 머리 식히러 왔소", "장기도 몸에 좋다 하여 배우는 중이오"],
      move: ["꽤 괜찮은 수군요", "음, 맥이 고르구려", "그 수엔 감초가 들어갔소?"],
      userCapture: ["아이고, 처방을 잘못 내렸구려", "이 정도는 금방 낫소"],
      userBigCapture: ["내 차가! 침이라도 놓아야겠소 😵", "이건 중병이오…"],
      userCheck: ["장군이라니, 맥박이 빨라지는구려"],
      aiCapture: ["약이 잘 들었구려!", "명의는 기회를 놓치지 않소"],
      aiCheck: ["장군이오! 진맥 결과 위급하오"],
      undo: ["의원은 환자를 내치지 않소. 물러드리리다"],
      aiWin: ["이겼소?! 이것도 처방전에 적어 두겠소"],
      aiLose: ["그대 수가 명약이구려. 졌소 😅"],
      draw: ["비겼구려. 둘 다 건강하오"],
    },
  },
  {
    id: "kimjeongho",
    name: "김정호",
    rank: "12급",
    desc: "판 구석구석을 걸어 다님",
    emoji: "🗺️",
    ai: { depth: 1, ms: 400, noise: 1.8, blunder: 0.18 },
    lines: {
      greet: ["대동여지도 그리듯 판을 한번 훑어보겠소", "장기판도 결국 지도요"],
      move: ["꽤 괜찮은 수군요", "그 길은 지도에 표시해 두겠소", "오, 처음 보는 길이오"],
      userCapture: ["길을 잘못 들었구려", "이 고개는 험하구려"],
      userBigCapture: ["내 차가… 지도에서 지워야겠소", "크게 길을 잃었소"],
      userCheck: ["장군이라… 샛길을 찾아야겠소"],
      aiCapture: ["지름길을 찾았소!", "발로 뛴 보람이 있구려"],
      aiCheck: ["장군이오! 이 길은 막다른 길이오"],
      undo: ["되돌아가는 것도 길이오"],
      aiWin: ["판 전체가 내 지도 안에 있었소!"],
      aiLose: ["그대가 더 좋은 길을 알았구려"],
      draw: ["오늘은 여기까지 걸었소"],
    },
  },
  {
    id: "jeongyakyong",
    name: "정약용",
    rank: "9급",
    desc: "책은 많이 읽었어요",
    emoji: "📜",
    ai: { depth: 1, ms: 400, noise: 1.2, blunder: 0.1 },
    lines: {
      greet: [
        "유배지에서 장기 책을 좀 읽었소. 한 수 배우겠소",
        "실사구시! 장기도 실전이 중요하지요",
      ],
      move: [
        "허허, 꽤 괜찮은 수군요",
        "그 수는 목민심서에도 없는 수로다",
        "흥미롭소. 기록해 두겠소",
      ],
      userCapture: ["으음, 거중기로도 못 막았구려", "그건 내가 잘못 짚었소"],
      userBigCapture: ["내 차를… 이건 책에 없던 일이오!", "허허, 크게 당했구려"],
      userCheck: ["장군이라… 궁을 옮겨야겠소"],
      aiCapture: ["실학의 힘이오", "책에서 본 대로구려!"],
      aiCheck: ["장군이오. 이치대로 두었을 뿐이오"],
      undo: ["배움엔 되돌아봄이 필요하지요. 물러드리리다"],
      aiWin: ["이론이 실전에서도 통했구려!"],
      aiLose: ["잘 두시는구려. 이번 대국은 꼭 기록해 두겠소"],
      draw: ["비겼구려. 다음 판도 기대되오"],
    },
  },
  {
    id: "hwanghui",
    name: "황희",
    rank: "6급",
    desc: "너도 옳고 나도 옳소",
    emoji: "🧓",
    ai: { depth: 2, ms: 600, noise: 1, blunder: 0.06 },
    lines: {
      greet: ["허허, 너도 옳고 나도 옳으니 한 판 둡시다", "청렴하게 두겠소"],
      move: ["꽤 괜찮은 수군요", "그대 말도 옳소", "허허, 그 수도 일리가 있구려"],
      userCapture: ["그대가 옳소", "그것도 옳은 수요"],
      userBigCapture: ["허허… 그대가 아주 옳구려", "내 차를… 그래도 그대가 옳소"],
      userCheck: ["장군이라, 그것도 옳은 말이오"],
      aiCapture: ["이번엔 나도 옳았소", "허허, 받아 가겠소"],
      aiCheck: ["장군이오. 이것도 옳은 수요"],
      undo: ["무르는 것도 옳은 일이오"],
      aiWin: ["허허, 오늘은 내가 조금 더 옳았구려"],
      aiLose: ["그대가 옳았소. 깔끔히 인정하오"],
      draw: ["둘 다 옳았구려"],
    },
  },
  {
    id: "gyebaek",
    name: "계백",
    rank: "3급",
    desc: "황산벌의 결사대",
    emoji: "🛡️",
    ai: { depth: 2, ms: 700, noise: 0.6, blunder: 0.03 },
    lines: {
      greet: ["오천 결사대의 각오로 두겠소", "물러섬은 없소"],
      move: ["꽤 괜찮은 수군요", "흠, 만만치 않구려", "황산벌보다 험하구려"],
      userCapture: ["한 명이 쓰러졌을 뿐이오", "아직 결사대는 남았소"],
      userBigCapture: ["크윽… 그래도 물러서지 않소", "내 차를! 끝까지 싸우겠소"],
      userCheck: ["장군이라! 궁을 사수하라!"],
      aiCapture: ["결사대의 일격이오!", "가져가겠소"],
      aiCheck: ["장군이오! 각오하시오"],
      undo: ["한 번은 기회를 주겠소"],
      aiWin: ["결사대가 이겼소!"],
      aiLose: ["후회는 없소. 멋진 승부였소"],
      draw: ["결판이 나지 않았구려"],
    },
  },
  {
    id: "kimyusin",
    name: "김유신",
    rank: "1급",
    desc: "삼국을 통일한 장수",
    emoji: "🐎",
    ai: { depth: 2, ms: 800, noise: 0.35, blunder: 0.01 },
    lines: {
      greet: ["화랑의 기개로 상대하겠소!", "말의 목을 벨 각오로 두겠소이다 🐎"],
      move: ["꽤 괜찮은 수군요", "제법이오. 화랑도에 들어올 만하오", "음, 그 수는 예상 밖이오"],
      userCapture: ["크윽, 한 걸음 물러서겠소", "좋은 수였소"],
      userBigCapture: ["내 차를 잡다니… 대단하오!", "이런, 내 말이 또 엉뚱한 데로 갔구려"],
      userCheck: ["장군이라! 궁을 지켜라!"],
      aiCapture: ["통일의 길은 멀지 않았소", "가져가겠소!"],
      aiCheck: ["장군이오! 항복하시겠소?"],
      undo: ["이번 한 번만이오"],
      aiWin: ["삼국에 이어 장기판도 통일했구려!"],
      aiLose: ["훌륭하오. 그대야말로 진정한 장수요"],
      draw: ["무승부라… 오늘은 휴전이오"],
    },
  },
  {
    id: "euljimundeok",
    name: "을지문덕",
    rank: "초단",
    desc: "유인하고 몰아치는 전술가",
    emoji: "🏹",
    ai: { depth: 3, ms: 900, noise: 0.25, blunder: 0 },
    lines: {
      greet: ["살수에서처럼 정중히 맞이하겠소", "그대의 신묘한 책략, 구경 좀 하겠소"],
      move: [
        "신묘한 책략은 하늘의 이치를 다했고… 꽤 괜찮은 수군요",
        "흠, 그 길로 오시겠다?",
        "좋은 수요. 하지만 이미 알고 있었소",
      ],
      userCapture: ["일부러 내어준 것이오", "미끼를 무셨구려… 아니, 진짜 잡혔소?"],
      userBigCapture: ["이건 계획에 없었소!", "전공이 이미 높으니 만족을 알고 그치는 게 어떻소?"],
      userCheck: ["장군이라… 물러설 줄도 알아야 하는 법이오"],
      aiCapture: ["유인은 끝났소. 이제 몰아칠 차례요", "살수대첩이 따로 없구려"],
      aiCheck: ["장군이오. 퇴로는 막혔소"],
      undo: ["한 번은 길을 열어드리리다"],
      aiWin: ["살수에 이어 장기판에서도 이겼구려"],
      aiLose: ["그대의 책략이 나보다 한 수 위였소"],
      draw: ["팽팽한 대치였소"],
    },
  },
  {
    id: "yeongaesomun",
    name: "연개소문",
    rank: "2단",
    desc: "당나라도 막아낸 고구려의 실력자",
    emoji: "🗡️",
    ai: { depth: 3, ms: 1100, noise: 0.1, blunder: 0 },
    lines: {
      greet: ["안시성처럼 단단히 지키겠다", "칼 다섯 자루를 찬 기분으로 두겠소"],
      move: ["꽤 괜찮은 수군요", "그 정도로 고구려는 안 무너지오", "흥, 계산된 수요?"],
      userCapture: ["작은 성 하나 내준 것뿐이오", "대가를 치를 것이오"],
      userBigCapture: ["…제법이구려. 이제 진심으로 상대하겠소", "내 차를 잡다니!"],
      userCheck: ["장군이라… 성문은 아직 굳건하오"],
      aiCapture: ["고구려의 기상이오!", "가져가겠소"],
      aiCheck: ["장군이오. 물러서시오"],
      undo: ["이번 한 번뿐이오"],
      aiWin: ["고구려는 지지 않소"],
      aiLose: ["그대 앞에선 나도 물러나야겠구려"],
      draw: ["팽팽했소. 다시 붙읍시다"],
    },
  },
  {
    id: "gangamchan",
    name: "강감찬",
    rank: "3단",
    desc: "귀주에서 대승을 거둔 명장",
    emoji: "⚔️",
    ai: { depth: 4, ms: 1300, noise: 0.05, blunder: 0 },
    lines: {
      greet: ["귀주에서처럼 바람이 내 편이길 바라오", "성실하게 상대하겠소"],
      move: ["꽤 괜찮은 수군요. 하지만 아직이오", "음, 신중하구려", "그 수, 기억해 두겠소"],
      userCapture: ["흠, 대가를 치르게 될 것이오", "좋은 수였소"],
      userBigCapture: ["…방심했구려. 다시는 없을 것이오", "내 차를 잡다니, 대단하오"],
      userCheck: ["장군이라… 아직 무너지지 않았소"],
      aiCapture: ["귀주의 바람이 불었구려", "가져가겠소"],
      aiCheck: ["장군이오"],
      undo: ["이번만 물러드리겠소"],
      aiWin: ["귀주대첩만큼 값진 승리였소"],
      aiLose: ["그대의 실력에 경의를 표하오"],
      draw: ["실로 팽팽한 승부였소"],
    },
  },
  {
    id: "gwanggaeto",
    name: "광개토대왕",
    rank: "4단",
    desc: "판 전체를 넓혀 가는 정복왕",
    emoji: "🐉",
    ai: { depth: 5, ms: 1600, noise: 0, blunder: 0 },
    lines: {
      greet: ["영토를 넓히듯 판을 넓혀 가겠다", "만주 벌판보다 좁구나. 시작하지"],
      move: ["꽤 괜찮은 수군요", "그 땅도 곧 내 것이 되리라", "흠, 쉽지 않은 상대로다"],
      userCapture: ["땅 한 뼘을 내주었을 뿐", "다시 되찾을 것이다"],
      userBigCapture: ["…대단하구나. 짐의 차를 잡다니", "이 판, 쉽지 않겠어"],
      userCheck: ["장군이라… 짐은 흔들리지 않는다"],
      aiCapture: ["영토가 넓어졌도다", "가져가겠다"],
      aiCheck: ["장군이다. 항복하라"],
      undo: ["관대함도 왕의 덕목이지"],
      aiWin: ["이 판도 짐의 영토로다"],
      aiLose: ["짐을 이기다니… 그대의 이름을 비석에 새기리라"],
      draw: ["오늘은 국경을 그대로 두지"],
    },
  },
  {
    id: "yisunsin",
    name: "이순신",
    rank: "5단",
    desc: "단 한 번도 지지 않은 장군",
    emoji: "🐢",
    ai: { depth: 6, ms: 2200, noise: 0, blunder: 0 },
    lines: {
      greet: [
        "필사즉생 필생즉사. 한 판 두어 봅시다",
        "바다에서처럼, 장기판에서도 물러서지 않겠소 🐢",
      ],
      move: ["꽤 괜찮은 수군요", "그 수, 이미 내다보았소", "흠. 조류가 바뀌고 있구려"],
      userCapture: ["작은 손실일 뿐이오", "흔들리지 마라. 침착하게"],
      userBigCapture: [
        "신에게는 아직 열두 척의 배가 남아 있사옵니다",
        "…다시는 이런 일이 없을 것이오",
      ],
      userCheck: ["장군이라… 학익진으로 맞서겠소"],
      aiCapture: ["학익진이 완성되었소", "명량의 물살처럼!"],
      aiCheck: ["장군이오. 퇴로는 없소"],
      undo: ["전장에선 무를 수 없으나… 이번만이오"],
      aiWin: ["전투는 끝났소. 좋은 대국이었소"],
      aiLose: ["…그대가 나를 이겼소. 실로 대단하오 🐢"],
      draw: ["승부를 가리지 못했구려. 다음을 기약하겠소"],
    },
  },
];

export const DEFAULT_JANGGI_BOT = "kimyusin";

/** 랭킹 표시용: 봇 id → "이순신(5단)" */
export function janggiOppLabel(id: string) {
  const b = JANGGI_BOTS.find((x) => x.id === id);
  return b ? `${b.name}(${b.rank})` : id;
}
